# Generated by Django 5.2.6 on 2025-09-22 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
