# Generated by Django 5.2.6 on 2025-09-29 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'coin')},
        ),
    ]
